import Head from 'next/head'
import { useState } from 'react'
import Header from "../components/Header"
import HomePage from '../components/HomePage'
import SideBarMenu from "../components/SideBarMenu"

export default function Home() {
  
  return (
    <div className="h-full w-screen bg-teal-50 overflow-x-hidden">
      <Head>
        <title>Crypto Verse</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <main className="flex flex-col lg:px-24 px-6">
        <HomePage />
      </main>
    </div>
  )
}